### ISSUE TITLE
Add node counts to status when using network monitor DID

### ISSUE THREAD

**Issue by swcurran** [hyperledger/indy-node-monitor#20]
When not in anonymous mode, suggest that the `--status` result also return the following fields:

From `Pool_info`:

- `Unreachable_nodes_count`
- `Reachable_nodes_count`
- `Total_nodes_count`
- Possibly `Suspicious_nodes` if it is a count -- not if it is an array.

From `Hardware`:

- `HDD_used_by_node`

Nice to have from the 'Extractions' node -- trickier because the values are in text:

- node-control status: Memory: <value> and Tasks: <value>
  - as `node-control-memory` and `node-control-tasks`
- indy-node_status: Memory: <value> and Tasks: <value>
  - as `indy-node-memory` and `indy-node-tasks`

**Comment by swcurran** [comment]
Note that I would like those values in all cases, so we can just feed the numbers into a graph and see how the change.

**Comment by WadeBarnes** [comment]
I'll think about this a bit.  The purpose of `--status` was to provide more of a green/red light status summary of the node.  Unreachable nodes (counts and list), for instance, are surfaced when detected, otherwise all nodes are reachable.  I agree with adding `Suspicious_nodes` to the issue detection.  That said detected issues (and the status summary) are available regardless of whether you get the full results or opt for just the status summary using `--status`.

Right now it feels like a monitoring system that is tracking/graphing these metrics (or any metrics) historically should be sourcing the data from the full results and not using `--status`.

**Comment by swcurran** [comment]
Fair enough.  Feel free to close this if we're not going to do it. For me it was worth the exercise of going through the response is detail.
